
rocket-mq:
  producer:
    enabled: true
    default-m-q-producer-configs:
      - namesrvAddr: 10.0.3.2:9876
        producerGroup: TEST_PRODUCER_GROUP1
      - namesrvAddr: 10.0.3.2:9876
        producerGroup: TEST_PRODUCER_GROUP2
server:
  port: 8050