
rocket-mq:
  producer:
    enabled: true
    namesrv-addr:
    default-mq-producer-configs:
      - namesrvAddr:
        producerGroup: TEST_PRODUCER_GROUP1
        supportTransaction: true
      - namesrvAddr:
        producerGroup: TEST_PRODUCER_GROUP2
  consumer:
    enabled: true
    namesrv-addr:


server:
  port: 8050